"""Align PROVENANCE_DIFF.md with the statistical-reproducibility framing, and
record the HuggingFace second-repository search result."""
import io
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import common as C

p = os.path.join(C.RESULTS, "PROVENANCE_DIFF.md")
s = io.open(p, encoding="utf-8").read()

# 1. record the second-repo search under "### HuggingFace"
OLD = ("This also matches the hash pinned inside\n"
       "`configs/AL3NI_ROUND285_FINAL_UNSEALING_RESULT.txt`, which is public and identical.")
NEW = ("""**Searched for a second repository holding `pilot25_matpes_pbe_lora_v1.model`.**
None exists. `HfApi.list_models(author=...)` returns exactly one repository for
`asiri1` and nothing for the spellings `asiri1108`, `Asiri1108`, `asiri`, `asiri-1`
or `asiri11`; a full-text search for `pilot25` returns no result. The commit history
of `asiri1/al3ni-mace` has four commits, and listing the file tree at each revision
confirms the only model ever uploaded is `al3ni_combined227_lora_v1.model` - nothing
was published and later removed:

| Revision | Files |
|---|---|
| `2bbf8d40788c` | `.gitattributes` |
| `f5740c805a69` | `.gitattributes`, `al3ni_combined227_lora_v1.model` |
| `5f64e2d0308e` | + `README.md` |
| `3f35327ae3bf` (main) | unchanged |

`pilot25` is therefore confirmed **MISSING FROM PUBLIC RELEASE**, and the VALIDATION-18
and three-way analyses remain not publicly reproducible.

This also matches the hash pinned inside
`configs/AL3NI_ROUND285_FINAL_UNSEALING_RESULT.txt`, which is public and identical.""")
assert OLD in s
s = s.replace(OLD, NEW, 1)

# 2. replace the closing framing with the statistical one
OLD2 = s[s.index("### How to read this"):]
NEW2 = """### How to read this: statistical, not bitwise

Hash-irreproducibility of a GPU training run is the normal state of affairs. It is
**not** a defect, and it is **not** evidence of tampering or of code divergence - the
code here demonstrably has not diverged.

The reproducibility property that matters for a fitted interatomic potential is
statistical, and it is the one this validation confirms:

> **Three independent seeds (20260811 / 20260812 / 20260813), trained on identical
> data with identical hyperparameters, agree to 0.078 meV/atom in overall error - far
> inside the measured 0.43 meV/atom seed-noise floor.** Their reserved-19 maxima
> (2.5232 / 2.4333 / 2.6183) reproduced the recorded values exactly, on a different
> operating system, PyTorch version and processor, and the anchoring configuration
> (cfg060) was identical across all three.

A bitwise hash match would demonstrate less than that: it would show one run repeated,
not that the training procedure lands in the same place from different starting noise.

The corresponding limit on the claim is that two of those three seeds are unpublished,
so the statistical evidence is currently checkable only inside this validation. That is
precisely why releasing them is ranked first in the RELEASE_TODO section of
`results/VALIDATION_REPORT.md`: about 22 MB converts the project's central threshold
from asserted to independently verifiable.

The accurate provenance statement is therefore:

> The published artifact `al3ni_combined227_lora_v1.model` is verified identical to the
> file that was validated and to the file named in the sealed unsealing record. The
> code and configuration that produced it are public and unmodified. Its reproducibility
> is established statistically across seeds, not bitwise; bitwise regeneration would
> require a pinned container and enforced deterministic kernels, and is not claimed.

---

*Generated by `scripts/provenance_diff.py` and `scripts/write_provenance_diff.py`.*
*Machine-readable form: `results/provenance_diff.json`.*
"""
s = s[:s.index("### How to read this")] + NEW2

io.open(p, "w", encoding="utf-8").write(s)
print("PROVENANCE_DIFF.md updated: HF second-repo search + statistical framing")
