"""One-shot patch: insert the provenance note and RELEASE_TODO into phase17_report.py."""
import io
import os

p = os.path.join(os.path.dirname(os.path.abspath(__file__)), "phase17_report.py")
s = io.open(p, encoding="utf-8").read()

ANCHOR = "# ------------------------------------------------- seal status (mandatory)"

NOTE = r'''# ------------------------------------------------ provenance (public source)
w("## Provenance and public-source verification")
w()
w("Every artifact this validation consumed was re-fetched from public sources only")
w("(`git clone` of `Asiri1108/ni-al-mlip` and `Asiri1108/NiAl_MACE`, `huggingface_hub`,")
w("and the upstream `ACEsuit/mace-foundations` release) and compared by SHA256 against")
w("the local copies actually used. Full detail: `results/PROVENANCE_DIFF.md`.")
w()
w("**33 artifacts byte-identical, 0 different, 10 missing from the public release.**")
w("The ten missing are all model checkpoints; every dataset, split, config and status")
w("file is public and identical.")
w()
w("### The CRLF trap")
w()
w("A plain `git clone` on Windows reports **32 of 43 artifacts as DIFFERENT**. That is")
w("false. Where `core.autocrlf=true`, git rewrites LF to CRLF on checkout and every")
w("text artifact's hash changes. The tell is that the public copy of")
w("`ni_al_combined227_dft.extxyz` comes out exactly 2,266 bytes larger than the local")
w("one - precisely its line count (227 x 2 header lines + 1,812 atom lines).")
w()
w("**Clone with this flag, or you will wrongly conclude the release was tampered with:**")
w()
w("```")
w("git -c core.autocrlf=false clone https://github.com/Asiri1108/ni-al-mlip.git")
w("git -c core.autocrlf=false clone https://github.com/Asiri1108/NiAl_MACE.git")
w("```")
w()
w("This warning belongs in the public repository README as well as here; a ready-to-")
w("paste block is provided in `results/README_PROVENANCE_SNIPPET.md`.")
w()
w("### Identity of the model under test")
w()
w("The model this validation tested, the model published on HuggingFace, and the hash")
w("pinned inside the sealed unsealing record are **the same file**, and all three are")
w("confirmable from public sources:")
w()
w("| Claim | SHA256 | Source |")
w("|---|---|---|")
w("| Model under test | `e4fd54cc...` | local artifact, hashed in this validation |")
w("| Published model | `e4fd54cc...` | `huggingface.co/asiri1/al3ni-mace` |")
w("| Hash pinned in the sealed record | `e4fd54cc...` | `configs/AL3NI_ROUND285_FINAL_UNSEALING_RESULT.txt`, public and identical |")
w()
w("The base model is likewise verifiable: `MACE-matpes-pbe-omat-ft.model`, `e618ad58...`,")
w("matching the pin in the public `pilot25_matpes_pbe_lora_v1_PROVENANCE.txt`.")
w()
w("### NOT reproducible by a third party")
w()
w("Ten checkpoints are unpublished. HuggingFace hosts exactly one model, and that")
w("repository's commit history confirms no other model was ever uploaded and later")
w("removed; no second account or repository exists. Consequently the following results,")
w("though correct as reported here, **cannot currently be independently re-derived from")
w("public artifacts**:")
w()
w("1. **The 2.6183 threshold derivation.** The bar is the maximum across seeds")
w("   20260811/812/813. Only seed 20260811 is public, so the threshold itself cannot be")
w("   re-derived - only its middle contributing value, 2.5232, is recomputable.")
w("2. **The seed noise floor.** The 0.078 meV/atom cross-seed spread requires seeds")
w("   20260812 and 20260813.")
w("3. **Phase 16, the data-efficiency curve.** Eight of its nine points need unpublished")
w("   checkpoints, leaving a one-point curve. Every dataset it uses is public; only the")
w("   models are missing.")
w()
w("Also affected: the three-way model comparison degrades to two-way (base vs")
w("combined227, both public - the 4.3x energy and 15.7x force headline survives), and")
w("the VALIDATION-18 anomaly breakdown needs `pilot25`. The *contamination* finding")
w("within it survives, being a pure set-membership check over public datasets.")
w()
w("### What reproducibility means here: statistical, not bitwise")
w()
w("Bitwise regeneration of the model from source is **not expected**, and its absence is")
w("not a defect. The training code is public and demonstrably unmodified - 148 of 148")
w("shared scripts are byte-identical, and the public repository is newer only by four")
w("additive zero-shot analysis scripts that touch neither training nor any threshold.")
w("What prevents bitwise reproduction is environmental: CUDA non-determinism with no")
w("determinism flags set, and an un-containerised toolchain pin.")
w()
w("**The demonstrated claim is statistical: three independent seeds trained on identical")
w("data agree to 0.078 meV/atom, far inside the 0.43 meV/atom noise floor.** That is the")
w("meaningful reproducibility property for a fitted interatomic potential, and it is the")
w("one this validation confirms. A bitwise hash match would demonstrate less.")
w()
w("The honest limit of that claim: the three-seed evidence is checkable only inside this")
w("validation, because two of the three seeds are unpublished. That is exactly why")
w("releasing them is the highest-value action in the list below.")
w()

''' + ANCHOR

assert ANCHOR in s, "anchor not found"
s = s.replace(ANCHOR, NOTE, 1)

FOOT = 'w("---")\nw()\nw("*Generated by `scripts/phase17_report.py` from the files in `results/`. No value in")'

TODO = r'''w("## RELEASE_TODO - what to publish to close the reproducibility gap")
w()
w("Total outstanding: ten `.model` files, roughly 11 MB each, about 120 MB. Every")
w("dataset, split, config and status file they would be evaluated against is **already**")
w("public and verified byte-identical, so nothing else needs uploading.")
w()
w("### Priority 1 - the single highest-value upload (about 22 MB)")
w()
w("| File | Size |")
w("|---|---|")
w("| `al3ni_combined227_seed20260812_lora_v1.model` | ~11 MB |")
w("| `al3ni_combined227_seed20260813_lora_v1.model` | ~11 MB |")
w()
w("These two restore **the derivation of the 2.6183 acceptance threshold** - currently")
w("the single most important number in the project that a third party cannot re-derive -")
w("and with it the cross-seed noise floor that underwrites the statistical")
w("reproducibility claim above. Two files, about 22 MB, convert the project's central")
w("threshold from asserted to independently checkable. Nothing else on this list comes")
w("close in value per megabyte.")
w()
w("### Priority 2 - Phase 16 enablers (about 88 MB, eight files)")
w()
w("| File | Data-efficiency point |")
w("|---|---|")
w("| `pilot25_matpes_pbe_lora_v1.model` | N = 25; also restores the three-way comparison and the VALIDATION-18 anomaly breakdown |")
w("| `dataset100_matpes_pbe_lora_v1.model` | N = 100 |")
w("| `al3ni_combined113_lora_v1.model` | N = 113 |")
w("| `al3ni_combined127_lora_v1.model` | N = 127 |")
w("| `al3ni_combined129_lora_v1.model` | N = 129 |")
w("| `al3ni_combined211_lora_v1.model` | N = 211 |")
w("| `al3ni_combined218_lora_v1.model` | N = 218 |")
w("| `al3ni_combined220_lora_v1.model` | N = 220; also restores the 2.3865 -> 2.5232 regression evidence in limitation 3 |")
w()
w("These restore the data-efficiency curve - the result most likely to be independently")
w("publishable, since it answers how much DFT data LoRA fine-tuning of MACE actually")
w("needs for Ni-Al. `pilot25` is the most valuable of the eight, carrying three separate")
w("analyses on its own.")
w()
w("### Priority 3 - documentation, no upload required")
w()
w("Add the `core.autocrlf=false` clone instruction to the public README")
w("(`results/README_PROVENANCE_SNIPPET.md` is ready to paste). Without it, any Windows")
w("user attempting to verify the release will see 32 spurious hash mismatches.")
w()
''' + FOOT

assert FOOT in s, "footer not found"
s = s.replace(FOOT, TODO, 1)

io.open(p, "w", encoding="utf-8").write(s)
print("patched: provenance note + RELEASE_TODO")
