"""Render results/PROVENANCE_DIFF.md from results/provenance_diff.json."""
import os
import sys
import json
import collections

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import common as C

d = json.load(open(os.path.join(C.RESULTS, "provenance_diff.json")))
rows, hf, base = d["rows"], d["huggingface"], d["base_model"]
L = []
w = L.append

w("# Provenance diff - public sources vs the artifacts the validation consumed")
w("")
w("**Mode: public-source only.** Permitted sources were `git clone` of the two public")
w("GitHub repositories, `huggingface_hub`, and the upstream MACE foundation release.")
w("No `D:/` path, no `/workspace` path and no `.tar.gz` was used to obtain a public")
w("copy. The local archive was read but not modified or deleted; it is the left-hand")
w("side of every comparison below.")
w("")
w("**Sources**")
w("")
w("| Source | Reference |")
w("|---|---|")
w("| GitHub | `Asiri1108/ni-al-mlip` @ `21d0996` (2026-08-23) |")
w("| GitHub | `Asiri1108/NiAl_MACE` |")
w("| HuggingFace | `asiri1/al3ni-mace` |")
w("| Upstream | `ACEsuit/mace-foundations`, release `mace_matpes_0` (base model only) |")
w("")

w("## Methodological warning: the first diff was wrong")
w("")
w("A naive `git clone` on this machine reported **32 of 43 artifacts as DIFFERENT**.")
w("That was entirely an artefact. `core.autocrlf` is set to `true` globally here, so")
w("git rewrote every text file's line endings from LF to CRLF on checkout. The public")
w("copy of `ni_al_combined227_dft.extxyz` came out at 415,544 bytes against the local")
w("413,278 - a difference of exactly 2,266 bytes, which is precisely the file's line")
w("count (227 x 2 header lines + 1,812 atom lines).")
w("")
w("Re-cloning with `git -c core.autocrlf=false clone` made every one of those 32")
w("artifacts byte-identical. **Anyone repeating this diff on Windows must disable")
w("autocrlf, or they will conclude the public release has been tampered with.**")
w("")

counts = collections.Counter(r["status"] for r in rows)
w("## Step 1 - Result")
w("")
w("| Status | Count |")
w("|---|---|")
for k in ["IDENTICAL", "DIFFERENT", "MISSING FROM PUBLIC RELEASE"]:
    w("| %s | %d |" % (k, counts.get(k, 0)))
w("")
w("**No artifact is DIFFERENT.** Every artifact that exists in the public release is")
w("byte-identical to the copy the validation consumed. The only gap is that ten of the")
w("eleven model checkpoints are not published at all.")
w("")

for cat, title in [("model", "Models"), ("dataset", "Datasets"), ("config", "Config / status files")]:
    sub = [r for r in rows if r["category"] == cat]
    w("### %s" % title)
    w("")
    w("| Artifact | Public source | Status | SHA256 (local) |")
    w("|---|---|---|---|")
    for r in sub:
        src = r["public_source"] if r["public_source"] != "-" else "*(none)*"
        st = r["status"]
        st = "**%s**" % st if st != "IDENTICAL" else st
        w("| `%s` | %s | %s | `%s` |"
          % (os.path.basename(r["artifact"]), src, st, r["local_sha"][:16] + "..."))
    w("")

w("### Base model (upstream, not a project repo)")
w("")
w("| Artifact | Source | Status |")
w("|---|---|---|")
w("| `MACE-matpes-pbe-omat-ft.model` | %s | %s |" % (base["public_source"], base["status"]))
w("")
w("SHA256 `e618ad58...` matches the pin recorded in")
w("`configs/pilot25_matpes_pbe_lora_v1_PROVENANCE.txt`, which is itself public and")
w("identical. The base model is fully verifiable from public sources.")
w("")
w("### HuggingFace")
w("")
w("Repository `asiri1/al3ni-mace` contains exactly three files: `.gitattributes`,")
w("`README.md`, `al3ni_combined227_lora_v1.model`.")
w("")
w("- HF model SHA256: `%s`" % hf.get("model_sha256_huggingface", "?"))
w("- Local  model SHA256: `%s`" % hf.get("model_sha256_local", "?"))
w("- Status: **%s**" % hf["status"])
w("")
w("This also matches the hash pinned inside")
w("`configs/AL3NI_ROUND285_FINAL_UNSEALING_RESULT.txt`, which is public and identical.")
w("So the model under test, the published model, and the model named in the sealed")
w("unsealing record are all one and the same file, confirmed from public sources alone.")
w("")

w("## Step 2 - Blast radius")
w("")
w("The critical distinction: **no number in the completed validation changes**, because")
w("every input that is public is byte-identical. What changes is *reproducibility* -")
w("which conclusions a third party with only public access could independently re-derive.")
w("")
w("### Fully reproducible from public sources")
w("")
w("Phases **1, 2, 2b, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17** need only the")
w("`combined227` model (on HuggingFace), the `combined227` dataset, and config files -")
w("all present and identical. In particular:")
w("")
w("- **Phase 7 / 10 / 13 / 14** depend on `mu_Al` and `mu_Ni`, whose sole source")
w("  `STEPB_ELEMENTAL_REFERENCES_STATUS.txt` is public and identical.")
w("- **Phase 12**'s entire verdict rests on `LAMMPS_STAGE_A_SINGLE_POINT_STATUS.txt`,")
w("  which is public and identical.")
w("- **Phase 4**'s alpha-angle corroboration and **Phase 8**'s elastic cross-check rest")
w("  on the Stage B and Stage C status files, both public and identical.")
w("")
w("### Degraded")
w("")
w("| Analysis | Effect of the missing checkpoints |")
w("|---|---|")
w("| **Phase 3, three-way comparison** | Becomes **two-way**. `base` (public upstream) vs `combined227` (public) still gives the headline result that fine-tuning cuts energy MAE 4.3x and force MAE 15.7x. The `pilot25` middle term is lost, so the claim *\"combined227 improves on pilot25 in every column\"* is **not publicly reproducible**. |")
w("| **Phase 3.5, multi-seed** | **Unrunnable.** Seeds 20260812 and 20260813 are unpublished. The measured 0.078 meV/atom seed spread cannot be re-derived. |")
w("| **Threshold-derivation reproduction** | Degrades from three exact reproductions to **one**. Only seed 20260811's reserved-19 maximum (2.5232) can be recomputed publicly; the 2.4333 and 2.6183 values, and the finding that cfg060 anchors all three seeds, cannot. Since 2.6183 is the max across all three, **the locked threshold itself cannot be re-derived from public artifacts.** |")
w("| **Phase 16, data-efficiency curve** | **Unrunnable.** Eight of the nine points (N = 25, 100, 113, 127, 129, 211, 218, 220) require unpublished checkpoints. Only N = 227 survives - a one-point curve. The central research claim (~100 configurations suffices; 100 -> 227 buys only -16% energy MAE) is **not publicly reproducible**, even though every dataset it used is public. |")
w("| **Limitation 3 evidence** | Partly lost. The reserved-19 maximum regression 2.3865 -> 2.5232 needs `combined220`. The cross-seed confirmation that cfg107/cfg115 degrade in all three seeds needs the two seed checkpoints. Only the single-seed combined227 numbers remain reproducible. |")
w("| **Phase 16 val18 anomaly** | **Unrunnable.** The whole pilot25-vs-combined227 breakdown needs `pilot25`. Note the *contamination* finding itself survives, since it is a pure set-membership check over public datasets. |")
w("")
w("### What would restore full reproducibility")
w("")
w("Publishing the ten missing `.model` files - roughly 11 MB each, about 120 MB total.")
w("Nothing else is needed: every dataset, split, config and status file they would be")
w("evaluated against is already public and verified identical.")
w("")

w("## Training code: has it diverged?")
w("")
w("Reported separately, as requested. **This does not affect the validation, which")
w("tested the artifact, not the code that produced it.**")
w("")
w("### The code has NOT diverged")
w("")
w("| Comparison | Result |")
w("|---|---|")
w("| Scripts present in both copies | **148 / 148 byte-identical** |")
w("| Scripts differing | **0** |")
w("| Present only in the public repo | 4 |")
w("| Present only locally | 0 |")
w("")
w("The public repository is indeed newer - HEAD is `21d0996`, 2026-08-23, later than the")
w("local archive snapshot - but the difference is purely additive, and the four added")
w("files are all downstream analysis, not training:")
w("")
w("- `lammps_stage_b_relax_phase_matpes0_zeroshot.py`")
w("- `lammps_stage_b_report_matpes0_zeroshot.py`")
w("- `lammps_stage_b_run_all_matpes0_zeroshot.py`")
w("- `save_lammps_0K_zeroshot_structures.py`")
w("")
w("All four add a **zero-shot MACE-MATPES-PBE-0 LAMMPS baseline** for comparison against")
w("the fine-tuned model. None touches training, data assembly, or any threshold.")
w("`run_al3ni_combined227_mace_training.sh` and `al3ni_combined227_lora_v1.yaml` are both")
w("byte-identical to the versions used for the model under test.")
w("")
w("### Would rerunning them reproduce the pinned hash? Almost certainly not")
w("")
w("This was **not** tested empirically - it needs a CUDA GPU, which this machine does not")
w("have, and retraining is outside the permitted scope. The assessment below is from")
w("reading the pinned, byte-identical launch script and config.")
w("")
w("The reason is *environmental determinism*, not code drift:")
w("")
w("1. **The script cannot run unmodified anywhere else.** It hard-codes")
w("   `ROOT=/workspace/ni_al` and invokes the interpreter at")
w("   `/workspace/ni_al/envs/mace-py312-cu128/bin/mace_run_train`. It is a RunPod")
w("   container script, not a portable recipe.")
w("2. **Training is not performed by repository code at all.** The script is a thin")
w("   wrapper around upstream `mace_run_train` from MACE 0.3.16. Reproducibility is")
w("   therefore a property of the upstream package and the environment, not of this")
w("   repository.")
w("3. **The config sets `seed: 20260811` but no determinism controls.** There is no")
w("   `torch.use_deterministic_algorithms`, no `CUBLAS_WORKSPACE_CONFIG`. With")
w("   `device: cuda`, non-deterministic atomics and autotuned cuBLAS kernel selection")
w("   mean even the same machine need not reproduce bitwise-identical weights.")
w("4. **The original environment is pinned but not containerised in the public repo:**")
w("   Python 3.12.3, torch 2.8.0+cu128, CUDA 12.8, RTX 4090, driver 580.173.02. A")
w("   different torch or CUDA version changes kernel choice and floating-point")
w("   accumulation order, which changes the weights, which changes the SHA256.")
w("")
w("Two inputs that *could* have caused divergence are ruled out: `E0s: estimated` is")
w("deterministic given the training data, and that data is byte-identical; and")
w("`foundation_model: mace-matpes-pbe-0` resolves to the upstream checkpoint whose hash")
w("`e618ad58...` was verified identical.")
w("")
w("### How to read this")
w("")
w("Hash-irreproducibility of a GPU training run is the normal state of affairs and is")
w("**not** evidence of tampering or of code divergence - here the code demonstrably has")
w("*not* diverged. It does mean the honest provenance claim is narrower than")
w("\"reproducible from source\":")
w("")
w("> The published artifact `al3ni_combined227_lora_v1.model` is verified identical to")
w("> the file that was validated and to the file named in the sealed unsealing record.")
w("> The code and configuration that produced it are public and unmodified. Bitwise")
w("> regeneration of that artifact from source has **not** been demonstrated and should")
w("> not be expected without a pinned container and enforced deterministic kernels.")
w("")
w("---")
w("")
w("*Generated by `scripts/provenance_diff.py` and `scripts/write_provenance_diff.py`.*")
w("*Machine-readable form: `results/provenance_diff.json`.*")

out = os.path.join(C.RESULTS, "PROVENANCE_DIFF.md")
open(out, "w", encoding="utf-8").write("\n".join(L) + "\n")
print("wrote %s (%d lines)" % (out, len(L)))
